export const roleToLastNameList = [
  { role: 'host', lastNames: ['Hostdanews', 'Hosterson', 'Anchorman'] },
  { role: 'cohost', lastNames: ['McHostly', 'Hostly', 'Newsman'] },
  { role: 'detective', lastNames: ['Gumshoe', 'Holmes', 'Sleuthburger'] },
  { role: 'witness', lastNames: ['Sawdathing'] },
  { role: 'criminologist', lastNames: ['McCrimey'] },
  { role: 'mother', lastNames: ['Momsly'] },
  { role: 'player', lastNames: ['kickaball'] },
  { role: 'coach', lastNames: ['McCoach'] },
  { role: 'fan', lastNames: ['McFan'] },
  { role: 'analyst', lastNames: ['McAnalyst'] },
  { role: 'politician', lastNames: ['Kennedy'] },
  { role: 'politicalcorrespondent', lastNames: ['Policywise'] },
  { role: 'campaignstrategist', lastNames: ['Jones'] },
  { role: 'localperson', lastNames: ['Personson'] },
  { role: 'criminal', lastNames: ['McGuilty'] },
  { role: 'guestexpert', lastNames: ['Expertson'] },
  { role: 'fieldreporter', lastNames: ['Fieldsly', 'Fielderson'] },
];