export const roleToLastNameList = [
  { role: 'sports', lastNames: ['player', 'coach', 'fan', 'analyst'] },
  { role: 'crime', lastNames: ['criminal', 'detective', 'witness', 'criminologist'] },
  { role: 'other', lastNames: ['mother', 'man', 'lad'] },
  { role: 'host', lastNames: ['Hostdanews', 'Hosterson', 'Anchorman'] },
  { role: 'cohost', lastNames: ['McHostly', 'Hostly', 'McNewsman'] },
  { role: 'detective', lastNames: ['Gumshoe', 'Holmes', 'Sleuthburger'] },
  { role: 'witness', lastNames: ['Sawdathing'] },
  { role: 'criminologist', lastNames: ['McCrimey'] },
  { role: 'mother', lastNames: ['Momsly'] },
  { role: 'man', lastNames: ['Mansly'] },
  { role: 'lad', lastNames: ['Ladsly'] },
  { role: 'player', lastNames: ['kickaball'] },
  { role: 'coach', lastNames: ['McCoach'] },
  { role: 'fan', lastNames: ['McFan'] },
  { role: 'analyst', lastNames: ['McAnalyst'] },
  { role: 'politician', lastNames: ['Kennedy'] },
  { role: 'politicalcorrespondent', lastNames: ['Policywise'] },
  { role: 'campaignstrategist', lastNames: ['Jones'] },
  { role: 'localperson', lastNames: ['Personson'] },
  { role: 'criminal', lastNames: ['McGuilty'] },
  { role: 'guestexpert', lastNames: ['Expertson'] }
];